### ISSUE TITLE
No response received from Jupiter C+

### ISSUE THREAD

**Issue by Th3AL0** [tomquist/hame-relay#39]
Hi Team,

Was this already tested on a Jupiter C+ ?
Not able to get it to work ...

In HA
```
pollingInterval: 30
responseTimeout: 30
enableCellData: false
enableCalibrationData: false
enableExtraBatteryData: false
allowedConsecutiveTimeouts: 3
mqttProxyEnabled: false
devices:
  - deviceType: JPLS-8H
    deviceId: "36011150..."
    mac: "24197..."
inverse_forwarding: true
```

Logs:
```
Published to hame_energy/JPLS-8H/App/360111505341373838115739/ctrl: cd=1
Published to marstek_energy/JPLS-8H/App/9c6a9e3234eccd0c8938fc25735bf86138c8b4dd8c40d7e80ae4e91a28b5c7e8/ctrl: cd=1
No response received from 360111505341373838115739 within timeout period
Published to hm2mqtt/JPLS-8H/availability/360111505341373838115739: offline
Published to hame_energy/JPLS-8H/App/360111505341373838115739/ctrl: cd=1
Published to marstek_energy/JPLS-8H/App/9c6a9e3234eccd0c8938fc25735bf86138c8b4dd8c40d7e80ae4e91a28b5c7e8/ctrl: cd=1
No response received from 360111505341373838115739 within timeout period
Published to hm2mqtt/JPLS-8H/availability/360111505341373838115739: offline
Published to hame_energy/JPLS-8H/App/360111505341373838115739/ctrl: cd=1
Published to marstek_energy/JPLS-8H/App/9c6a9e3234eccd0c8938fc25735bf86138c8b4dd8c40d7e80ae4e91a28b5c7e8/ctrl: cd=1
No response received from 360111505341373838115739 within timeout period
Published to hm2mqtt/JPLS-8H/availability/360111505341373838115739: offline
```

Anything else that I can test or that yo need? 

Kr
Alex
