### ISSUE TITLE
Fail after update 1.1.0

### ISSUE THREAD

**Issue by Tryer23** [tomquist/hame-relay#8]
MQTT protocoll is totally strange:
hame_energy
HMA-1
App
0
ctrl = cd=13

config YAML:
```
inverse_forwarding: true
devices:
  - device_id: 360111504d4630373XXX724b
    mac: e88da6fXXX5f
    type: HMA-2
mqtt_uri: ""
```
